##### The random is a module presnet in the Numpy library. This module contains the functionw hichc are used for generating random numbers. This module contains some simple random data generation methods, some permutation and distribution function, and random generator functions.

In [8]:
import numpy as np

##### 1. np.random.rand(d0,d1,...,dn): Simple random with given shape

In [9]:
a = np.random.rand(5,2)
a

array([[0.09007198, 0.14043978],
       [0.61467904, 0.12594042],
       [0.68214802, 0.41799259],
       [0.8009483 , 0.82415254],
       [0.13538256, 0.0128075 ]])

##### 2. np.random.randn(d0,d1,....,dn): This function of random module return a sample from the "standard normal" distribution.

In [10]:
a = np.random.randn(2,2)
a

array([[-0.04207043,  0.43428746],
       [ 1.00492944, -0.46090106]])

##### 3. no.randomint(): This function of random module is used to generate random integers from inclusive low to exclusive high

In [14]:
a = np.random.randint(20,size=10)
a

array([ 3, 18,  1,  4,  8, 18, 18,  9, 18, 18])

##### 4. np.random.random_integers(): This function is used to generate random integers number of type np.int between low and high

In [15]:
a = np.random.random_integers(3)
a

C:\Users\migue\AppData\Local\Temp\ipykernel_22296\1099775208.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 3 + 1) instead
  a = np.random.random_integers(3)


3

##### 5. np.random_random_sample(): This function of random mmodule is used to generate random floats number in the half-open interval [0.0,1.0]

In [22]:
a = np.random.random_sample()
a

0.39838597948079124

In [24]:
a = np.random.random_sample(5)
a

array([0.78782629, 0.51603194, 0.53554482, 0.20796251, 0.38148352])

##### 6. np.random.random(): this function of random moduule is used to generate random floats number, in the half-open interval [0.0, 1.0]

In [20]:
a = np.random.random()
a

0.4401851657925083

In [26]:
a = np.random.random(5)
a

array([0.34397539, 0.51482657, 0.26688124, 0.61808919, 0.33467913])

##### 7. np.random.ranf(): This function of random module is used to generate random floats number in the half-open interval [0.0,1.0]

In [28]:
a = np.random.ranf()
a

0.582861192303319

In [30]:
a = np.random.ranf(5)
a

array([0.06241118, 0.9032984 , 0.63174417, 0.19634842, 0.00481728])

##### 8. np.random.sample(): This function of random module is used to generate random flats number in the ghalf-open interval [0.0.1.0] 

In [31]:
a = np.random.sample()
a

0.2972653200517017

In [33]:
a = np.random.sample(5)
a

array([0.21471294, 0.5399277 , 0.80295212, 0.09955538, 0.89315554])

##### 9. np.random.choice(a,b,[]): This function of random module is used to generate ranodm sample from a giuven 1-D array

In [37]:
a = np.random.choice(5,3)
a

array([2, 3, 1])

In [38]:
a = np.random.choice(5,3,[0.2,0.1,0.4,0.2,0.1])
a

array([0, 0, 3])

##### 10. np.random.bytes(): This function of random module is used to generate random bytes

In [39]:
a = np.random.bytes(7)
a

b'X8\x03\x8a\xb7"\xb2'