#### Numpy Basics

* ndarray.ndim: Number of axes (Dimensions) of array.
* ndarray.shape: The dimensions of array. This is a tuple of integer indicating the size of the array in each dimension.
* ndarray.size:  Total number of element of the array.
* ndarray.dtype: an object describing the type of the elements in the array
* ndarray.itemsize: the size in bytes of each element of the array. float64 = 8 (64/8)
* ndarray.data: the buffer containing the actual elements of the array. Normally, we won't need to use this attribute becaiuse we will access the elements in an array using indexing facilities

In [2]:
#Example
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [5]:
a.dtype.name

'int32'

In [6]:
a.itemsize

4

In [7]:
a.size

15

In [8]:
type(a)

numpy.ndarray

#### Array Creation
#### there are several ways to create arrays.

In [10]:
# 1. create an array form regular python list or tuple using the array function
a = np.array([2,3,4])
a

array([2, 3, 4])

In [11]:
a.dtype

dtype('int32')

In [12]:
b = np.array([1.2,3.5,5.1])
b

array([1.2, 3.5, 5.1])

In [13]:
b.dtype

dtype('float64')

In [14]:
# 2. Transform sequences of sequences into two-dimensional arrays, seuqnces of seuqences of sequences into three dimensional arrays, and so on.
b = np.array([(1.5,2,3) , (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [16]:
# 3. we can also be explicitly specified at creation time
c = np.array([[1,2] , [3,4]], dtype = complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [17]:
c.dtype

dtype('complex128')

In [19]:
# 4. Array of zeros
d = np.zeros((3,4), np.int16)
d
# default float64, but it an be specified via the key word argument dtype.

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [20]:
# 5. create with ones
d = np.ones((2,3,4) , dtype = np.int16)
d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [24]:
# 6. empty, create array with random, default data type float64
d = np.empty((2,3))
d

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [27]:
d.dtype

dtype('float64')

In [29]:
# 7. sequences of number, Numpy provides the arange function which is analogous to the python built-in range, but return an array
np.arange(10,30,5)


array([10, 15, 20, 25])

In [30]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [31]:
# when arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating precision. For this reason, it is usually better to use the funcion linspace that receives as an argument the number of elements that we want, insted of the step

np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])